# workflow schema 

type: array

items:
  type: object
  required:
    - instance
  patternProperties:
      
      '^instance$':
          oneOf:
            #- $ref: './components/exchange'
            - $ref: './common-definitions/#/definitions/Reference'  
      
      '^name$':
          type: string

      '^configuredBy$': 
          type: object        
