@startuml
  component  service1 <<instance>>
  interface produce1
  component  service2 <<instance>>
  interface consume2
  
  service1 -> produce1
  produce1 ..> consume2
  consume2 -> service2
@enduml
