msapi: "1.0.1"

metadata: 
  id: "ms_01_global_settings"
  title: "Global settings"
  description: Default queue and exchange settings

components:
    settings:  
        amqp:
            url: "amqps://xoilebqg:Nx46t4t9cxQ2M0rF2rIyZPS_xbAhmJIG@hornet.rmq.cloudamqp.com/xoilebqg"

        health:                       
            amqp:
                $ref: "#/components/settings/amqp"
            produce:
                exchange:
                    name: health_messages
            time_interval: 30000        
