title: Підсхема "produce"
descriptions: Налаштування публікувальника
type: object
additionalProperties: false
subschema: msapi.components.produce         

patternProperties:
  
  '^amqp':
    title: amqp
    descriptions: Налаштування брокера повідомлень
    $ref: "./connection"
    definitions: Налаштування з’єднання

  '^exchange$':
    title: exchange
    descriptions: Налаштування обмінника
    oneOf:
      - $ref: "./exchange"
        descriptions: Налаштування обмінника

      - $ref: "#/definitions/Reference"
        descriptions: Посилання на налаштування обмінника
  
  '^message$':
    title: message
    descriptions: Налаштування повідомлення 
    oneOf:
      - $ref: "#/definitions/Schema"
        descriptions: Посилання на налаштування повідомлень
      - $ref: "#/definitions/Reference"
        descriptions: Посилання на налаштування повідомлень

    