
type: object
additionalProperties: false
subschema: msapi.components.produce         

patternProperties:
  
  '^amqp':
    $ref: "./connection"

  '^exchange$':
    oneOf:
      - $ref: "./exchange"
      - $ref: "#/definitions/Reference"
  
  '^message$':
    oneOf:
      - $ref: "#/definitions/Schema"
      - $ref: "#/definitions/Reference"

    