title: Підсхема "produce"
description: Налаштування публікувальника
type: object
additionalProperties: false
subschema: msapi.components.produce         

patternProperties:
  
  '^amqp':
    title: amqp
    description: Налаштування брокера повідомлень
    $ref: "./connection"
    definitions: Налаштування з’єднання

  '^exchange$':
    title: exchange
    description: Налаштування обмінника
    oneOf:
      - $ref: "./exchange"
        description: Налаштування обмінника

      - $ref: "#/definitions/Reference"
        description: Посилання на налаштування обмінника
  
  '^message$':
    title: message
    description: Налаштування повідомлення 
    oneOf:
      - $ref: "#/definitions/Schema"
        description: Посилання на налаштування повідомлень
      - $ref: "#/definitions/Reference"
        description: Посилання на налаштування повідомлень

    