 @startuml
  
    queue  "test" <<Queue>> as Queue
    queue  "amqp_test_exchange" <<Exchange>> as Exchange #aaeeaa 
    frame  consumer{
        component  "consumer" <<Consumer>> as Consumer 
    }
    frame producer {
        component  "producer" <<Producer>> as Producer #aaeeaa
    }
    Producer -> Exchange
    Exchange -> Queue
    Queue -> Consumer
  
  @enduml  
