exchange: 
    name:                       # required name of exchange
                                
    mode: fanout                # required type of exchange. Available values  "fanout" or "topic" or "direct" 
    
    options:  # !!! options for assertExchange method call
        durable: true           # (boolean): if true, the exchange will survive broker restarts. Defaults to true.
        autoDelete: false       # (boolean): if true, the exchange will be destroyed once the number of bindings for which it is the source drop to zero. Defaults to false.
