# service schema

type: object
additionalProperties: false

patternProperties:
  '^config$':
      type: object
  
  '^consume$':
    $ref: "../components/consume"
    
  '^produce$':    
    $ref: "../components/produce"
   
